### PR TITLE
Basic CI setup

### PR DESCRIPTION
**Pull request by mophahr**
I hope I have removed all customer data...

Following the instructions in README.adoc and then running `/call_all_test_playbooks_without_jenkins.sh` should create some output in htmlreport.

### CODE REVIEW

**Comment by ericzolf** [comment]
I thought about it once more and actually we should keep it from the command line, there might be reasons to not use Jenkins and we could have an action for the hackathon to migrate the script from Perl to Python for easier maintenance :-) The other remarks still apply before I merge.

**Comment by mophahr** [comment]
>   I'm ready to discuss but I thought more about an approach using Jenkins and without the HTML export (it's nice but it's difficult to maintain and I'm not sure I want to have it continued as a standard).

I'm trying to that at the moment.

> Independently from this discussion, few comments:

>   * name demo-ci is too generic, perhaps callback-plugin-ci (or callback-plugin-cli-ci if we keep from the command line).

fixed
>   * junit2.pyc doesn't belong in here and should be git-ignored.

done
>   * if I simply call ./call_all_test_playbooks_without_jenkins.sh the HTML report shows all tests as failed. Is this normal?

Same here. I don't understand why that is the case, yet.
>   * I think there should be a few words in the readme that the HTML files are created from the XML log files, which are created using the junit2 callback plugin, which is itself an improvement of the standard junit callback plugin.

ACK
>   * actually it might be possible to use the standard junit plug-in in the meantime.
I'll have a look

**Comment by mophahr** [comment]
How do I rebase a fork? Is there a simpler way than deleting this PR , re-forking, and then copying in my stuff?

**Comment by sabre1041** [comment]
@mophahr To manage forks, you first want to make sure you have remotes setup for both your repository and the upstream `redhat-cop` repository. Assuming that your fork is configured as the _origin_ remote, you want to then add a new remote for the upstream repository. We'll call that _upstream_:

```
git remote add upstream git@github.com:redhat-cop/automate-cicd.git
```

Then you want to pull in the changes from the upstream

```
git fetch upstream
```

If you want to pull in changes on the master branch, check out the master branch and then pull it in:

```
git checkout master
git pull --rebase upstream master
```

**Pull request merged**
